# Site settings
title: lioil.win
email: lioilwin@qq.com
description: lioil.win

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
weibo:    3040028271
github:   lioilwin
# codepen:  username
# dribbble: username

# Comment
disqus_shortname: lifedis


# Google Analytics
google_analytics: UA-76382733-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
port: 80