# Site settings
title: LifeBlogs
email: wswfeng@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
 "Life博客 Life Blogs"
baseurl: ""
url: "http://lifegh.github.io"

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
weibo:    3040028271
github:   lifegh
# codepen:  username
# dribbble: username

# Comment
disqus_shortname: lifedis


# Google Analytics
google_analytics: UA-76382733-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
